blank_issues_enabled: false
contact_links:
  - name: ğŸ†• New Feature? - see [the how-to in our WIKI](https://github.com/AMI-Global/AMI.Docs/wiki/How%20to%20create%20a%20new%20feature%20request)
    url: https://github.com/AMI-Global/AMI.Docs/wiki/How%20to%20create%20a%20new%20feature%20request
    about: Ask Stig, Ronen or Mikkel for any clarifications needed.
  - name: ğŸ› Bug Reports - see [the how-to in our WIKI](https://github.com/AMI-Global/AMI.Docs/wiki/How%20to%20create%20a%20new%20bug%20report)
    url: https://github.com/AMI-Global/AMI.Docs/wiki/How%20to%20create%20a%20new%20feature%20request
    about: Ask Stig, Ronen or Mikkel for any clarifications needed.
