blank_issues_enabled: false
contact_links:
  - name: ğŸ†• Click here to see the WIKI guide on creating new feature requests.
    url: https://github.com/AMI-Global/AMI.Docs/wiki/How%20to%20create%20a%20new%20feature%20request
    about: Ask Stig, Ronen or Mikkel for any clarifications needed.
  - name: ğŸ› Click here to see the WIKI guide on creating new bug reports.
    url: https://github.com/AMI-Global/AMI.Docs/wiki/How%20to%20create%20a%20new%20bug%20report
    about: Ask Stig, Ronen or Mikkel for any clarifications needed.
