blank_issues_enabled: false
contact_links:
  - name: ğŸ†• New Feature? - see WIKI for how to create proper AMI feature requests.
    url: https://github.com/AMI-Global/AMI.Docs/wiki/guide.new_feature_issue
    about: Ask Stig, Ronen or Mikkel for any clarifications needed.
  - name: ğŸ› Bug Reports - see WIKI for how to create proper AMI bug reports.
    url: https://github.com/AMI-Global/AMI.Docs/wiki/guide.new_bugreport_issue
    about: Ask Stig, Ronen or Mikkel for any clarifications needed.
  - name: ğŸ“‹ Workflow - see WIKI for how comply with AMI's workflow procedures.
    url: https://github.com/AMI-Global/AMI.Docs/wiki/guide.workflows
    about: Ask Stig, Ronen or Mikkel for any clarifications needed.
